require("keys").setup() -- first: it records the mappings everything below sets
require("options")
require("lsp")
require("colorscheme")
require("netrw_pick").setup()
require("netrw_sidebar").setup()
require("netrw_tree").setup()
require("keymap")
require("find")
require("statusline")
