-- What each coding agent CLI needs to be launched and watched, and nothing
-- else. Everything version-specific about claude, codex and grok lives here so
-- the rest of the subsystem can talk about "an agent" without knowing which.
--
-- All three take the same shape of hook config, which is Claude Code's: an
-- event name mapping to groups of commands, with an optional matcher. Grok
-- documents the compatibility outright and reads ~/.claude/settings.json for
-- it; codex uses the same JSON. So there is one hook spec below, and the only
-- real difference is where each CLI wants it put:
--
--   claude  --settings <file>, a flag, so nothing is installed anywhere
--   codex   $CODEX_HOME, so a directory that mirrors the real one
--   grok    $GROK_HOME, likewise, with the hooks in config.toml
--
-- The mirrors symlink the real home entry by entry rather than copying it, so
-- credentials, sessions, skills and memory stay exactly where you left them and
-- keep working from a normal terminal. Only the hook file is ours. Nothing is
-- written to ~/.claude, ~/.codex or ~/.grok.
--
-- Two other things differ per CLI and so are decided here:
--
--   the screen   codex and grok take --no-alt-screen, so they draw inline and
--                what is on screen when they exit stays in the buffer. claude
--                has no such flag and takes over the alternate screen, where
--                nothing survives it at all. `inline` says which. Neither is
--                scrollback: all three repaint in place rather than letting
--                lines scroll off, so the buffer never holds more than a
--                screen of the conversation whatever we pass
--
-- Verified against claude 2.x, codex 0.147 and grok as installed: hooks fire,
-- grok's auth survives the mirror, and both --no-alt-screen flags exist.

local M = {}

local DATA = vim.fn.stdpath("data") .. "/agents"

M.DATA = DATA
M.INBOX = DATA .. "/inbox"
M.BIN = DATA .. "/bin"
M.HOOK = M.BIN .. "/agent-hook"

-- The lifecycle we care about, in the schema all three share. Kept small on
-- purpose: every event here has to mean something on the dashboard, and an
-- event that fires constantly costs a process spawn each time.
--
-- Codex has no Notification event and grok's fires for more than permission,
-- hence both it and PermissionRequest. Each CLI skips the names it does not
-- know, which is what makes one spec work for three.
local EVENTS = {
	{ event = "UserPromptSubmit" },
	{ event = "PostToolUse" },
	{ event = "Notification", matcher = "permission_prompt|elicitation_dialog" },
	{ event = "PermissionRequest" },
	{ event = "Stop" },
}

-- One process per hook, so this is a shell script rather than anything richer.
--
-- It is deliberately stable: codex asks you to trust hooks once and remembers
-- the answer, so a command that changed between runs would ask again every
-- time. The run id and the inbox are the only things baked in, and the inbox
-- is fixed for a given config directory.
local SCRIPT = [==[
#!/bin/sh
# Generated by lua/agent_cli.lua. Do not edit: it is rewritten on startup, and
# codex remembers having trusted this exact command.
#
# One lifecycle event, handed to Neovim. The event name arrives as an argument
# and the agent's own JSON payload on stdin.
#
# Every path exits 0. A hook that fails is a hook that interrupts the agent for
# the sake of a status icon, which is the wrong trade every time.
set -u

EVENT=$(printf '%s' "${1:-unknown}" | tr -cd 'A-Za-z0-9_-')
INBOX="${NVIM_AGENT_INBOX:-@INBOX@}"
[ -n "$INBOX" ] || exit 0
mkdir -p "$INBOX" 2>/dev/null || exit 0

BODY=$(cat 2>/dev/null || true)

# Only two things are wanted out of the payload, and pulling them with sed
# keeps what we emit entirely machine-generated: the JSON below is always
# valid, whatever the agent sent or failed to send.
field() {
    printf '%s' "$BODY" \
        | sed -n 's/.*"'"$1"'"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' \
        | head -1 | tr -cd 'A-Za-z0-9_.:/ -' | cut -c1-120
}
TOOL=$(field tool_name)
SESSION=$(field session_id)

# Which run this belongs to. Claude and grok pass our environment through to
# the hook so the id is simply there; codex does not, so the ancestry is
# recorded too and Neovim matches it against the process it started.
#
# Each ancestor is recorded as pid:name, and the name is the point: an agent
# that shells out to another agent produces a hook whose ancestry passes
# through the nested one on its way to ours. Neovim uses that to tell "my
# agent did something" from "my agent's agent did something", which otherwise
# arrive identically and end the parent's turn early.
RUN=$(printf '%s' "${NVIM_AGENT_RUN:-}" | tr -cd 'A-Za-z0-9_-')
PIDS=""
p=$$
n=0
while [ -n "$p" ] && [ "$p" -gt 1 ] 2>/dev/null && [ "$n" -lt 12 ]; do
    info=$(ps -o ppid=,comm= -p "$p" 2>/dev/null)
    [ -n "$info" ] || break
    parent=$(printf '%s' "$info" | awk '{print $1}')
    comm=$(printf '%s' "$info" | awk '{print $2}' | sed 's#.*/##' | tr -cd 'A-Za-z0-9_.-')
    PIDS="$PIDS $p:$comm"
    p="$parent"
    n=$((n + 1))
done

# Written under a dot-name and renamed, because Neovim is watching this
# directory and would otherwise read a file that is still being written.
stamp=$(date +%Y%m%d%H%M%S)
tmp="$INBOX/.$stamp.$$"
printf '{"event":"%s","run":"%s","pids":"%s","tool":"%s","session":"%s","at":%s}\n' \
    "$EVENT" "$RUN" "${PIDS# }" "$TOOL" "$SESSION" "$(date +%s)" > "$tmp" 2>/dev/null || exit 0
mv "$tmp" "$INBOX/$stamp.$$.json" 2>/dev/null || rm -f "$tmp" 2>/dev/null
exit 0
]==]

--- Hook groups in the shared JSON shape, pointing at our script.
local function hook_groups()
	local hooks = {}
	for _, spec in ipairs(EVENTS) do
		local group = { hooks = { { type = "command", command = M.HOOK .. " " .. spec.event } } }
		if spec.matcher then
			group.matcher = spec.matcher
		end
		hooks[spec.event] = { group }
	end
	return hooks
end

local function write(path, text)
	local f = io.open(path, "w")
	if not f then
		return false
	end
	f:write(text)
	f:close()
	return true
end

local function read(path)
	local f = io.open(path, "r")
	if not f then
		return nil
	end
	local text = f:read("*a")
	f:close()
	return text
end

--- Write the hook script, but only when it would change. Codex trusts a
--- command once and remembers; rewriting an identical file is harmless, but
--- being able to see that it did not change is worth the read.
local function install_script()
	vim.fn.mkdir(M.BIN, "p")
	vim.fn.mkdir(M.INBOX, "p")
	local want = SCRIPT:gsub("@INBOX@", M.INBOX)
	if read(M.HOOK) ~= want then
		if not write(M.HOOK, want) then
			return false, "could not write " .. M.HOOK
		end
	end
	vim.fn.setfperm(M.HOOK, "rwxr-xr-x")
	return true
end

--- A directory that stands in for a CLI's real home: every entry symlinked
--- across, except the ones we mean to own. Rebuilt additively on every call,
--- so a new file in the real home shows up, and anything the CLI has written
--- into the mirror (codex keeps its hook trust here) survives.
local function mirror(real, into, ours)
	if vim.fn.isdirectory(real) == 0 then
		return false, real .. " does not exist"
	end
	vim.fn.mkdir(into, "p")
	local own = {}
	for _, name in ipairs(ours) do
		own[name] = true
	end
	for _, path in ipairs(vim.fn.readdir(real)) do
		if not own[path] then
			local link = into .. "/" .. path
			-- getftype follows the link, so a dangling one reads as absent and
			-- is replaced rather than left broken.
			if vim.fn.getftype(link) == "" then
				vim.fn.delete(link)
				vim.uv.fs_symlink(real .. "/" .. path, link)
			end
		end
	end
	return true
end

--------------------------------------------------------------------------- --
-- the CLIs
--------------------------------------------------------------------------- --

local CLIS = {
	{
		name = "claude",
		label = "Claude Code",
		bin = "claude",
		-- No way to leave the alternate screen, so its terminal buffer keeps
		-- nothing at all once it exits. See `inline`.
		inline = false,
		-- A flag, so there is no home to mirror and nothing installed at all.
		prepare = function(self)
			local path = DATA .. "/claude-settings.json"
			local ok = write(path, vim.json.encode({ hooks = hook_groups() }))
			if not ok then
				return false, "could not write " .. path
			end
			self.settings = path
			return true
		end,
		argv = function(self, run)
			local argv = { self.bin }
			if self.settings then
				vim.list_extend(argv, { "--settings", self.settings })
			end
			if run.prompt then
				argv[#argv + 1] = run.prompt
			end
			return argv
		end,
	},

	{
		name = "codex",
		label = "Codex",
		bin = "codex",
		-- Codex will not run a hook it has not been told to trust, and asks
		-- once per home. That is the reason this mirror is kept rather than
		-- built per run: trust is recorded here, so you answer it once.
		note = "codex asks you to trust these hooks the first time it starts. Choose 'Trust all and continue'; it is remembered.",
		inline = true,
		prepare = function(self)
			local home = DATA .. "/codex-home"
			local ok, err = mirror(vim.env.HOME .. "/.codex", home, { "hooks.json" })
			if not ok then
				return false, err
			end
			if not write(home .. "/hooks.json", vim.json.encode({ hooks = hook_groups() })) then
				return false, "could not write " .. home .. "/hooks.json"
			end
			self.home = home
			return true
		end,
		env = function(self)
			return self.home and { CODEX_HOME = self.home } or {}
		end,
		argv = function(self, run)
			local argv = { self.bin }
			argv[#argv + 1] = "--no-alt-screen"
			if run.prompt then
				argv[#argv + 1] = run.prompt
			end
			return argv
		end,
	},

	{
		name = "grok",
		label = "Grok",
		bin = "grok",
		inline = true,
		-- Grok has no settings flag, so the same mirror trick, with the hooks
		-- appended to a copy of config.toml. Its own config is read rather
		-- than linked so the copy keeps whatever you have set.
		prepare = function(self)
			local home = DATA .. "/grok-home"
			local ok, err = mirror(vim.env.HOME .. "/.grok", home, { "config.toml" })
			if not ok then
				return false, err
			end
			local base = read(vim.env.HOME .. "/.grok/config.toml") or ""
			local toml = { base, "", "# Added by Neovim (lua/agent_cli.lua). Not your config." }
			for _, spec in ipairs(EVENTS) do
				toml[#toml + 1] = ("[[hooks.%s]]"):format(spec.event)
				if spec.matcher then
					toml[#toml + 1] = ('matcher = "%s"'):format(spec.matcher)
				end
				toml[#toml + 1] = ('hooks = [ { type = "command", command = "%s %s" } ]'):format(M.HOOK, spec.event)
			end
			if not write(home .. "/config.toml", table.concat(toml, "\n") .. "\n") then
				return false, "could not write " .. home .. "/config.toml"
			end
			self.home = home
			return true
		end,
		env = function(self)
			return self.home and { GROK_HOME = self.home } or {}
		end,
		argv = function(self, run)
			local argv = { self.bin }
			argv[#argv + 1] = "--no-alt-screen"
			if run.prompt then
				argv[#argv + 1] = run.prompt
			end
			return argv
		end,
	},
}

local by_name = {}
for _, cli in ipairs(CLIS) do
	by_name[cli.name] = cli
end

--- The CLIs actually on this machine. One you do not have is simply not
--- offered, which is the same rule find.lua uses for ripgrep.
function M.available()
	local out = {}
	for _, cli in ipairs(CLIS) do
		if vim.fn.executable(cli.bin) == 1 then
			out[#out + 1] = cli
		end
	end
	return out
end

function M.get(name)
	return by_name[name]
end

--- Put the hook script and each CLI's wiring in place. Returns the CLIs that
--- are wired and, separately, what went wrong for the ones that are not: a CLI
--- whose hooks could not be installed still runs, it just cannot say more than
--- whether it is alive.
function M.setup()
	local ok, err = install_script()
	if not ok then
		return {}, { err }
	end
	local wired, problems = {}, {}
	for _, cli in ipairs(M.available()) do
		local fine, why = true, nil
		if cli.prepare then
			fine, why = cli:prepare()
		end
		if fine then
			wired[#wired + 1] = cli
		else
			problems[#problems + 1] = cli.name .. ": " .. tostring(why)
		end
	end
	return wired, problems
end

return M
